---
title: "Tablero de Cantones"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(flexdashboard)
library(leaflet)
library(dplyr)
library(ggplot2) 
library(plotly) 
library(DT) 
library(rgdal) 
library(readr)
library(sf)
```

```{r}
cantones <-
  st_read(
    "cantones_simplificados.geojson", quiet = TRUE) %>%
st_transform(4326)
```

Column {data-width=650}
-----------------------------------------------------------------------

### MAPA

```{r}
leaflet() %>% 
  addTiles() %>%
  addPolygons(data = cantones, weight = 1.0, color = "blue") 
```

Column {data-width=350}
-----------------------------------------------------------------------

### TABLA

```{r}
cantones %>%
  st_drop_geometry() %>%
  select(provincia, canton, area) %>%
  arrange(desc(area)) %>%
  datatable(
    colnames = c("Provincia", "Canton", "Area (km2)"),
    options = list(
  pageLength = 5,
  language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')
    )
  )
  
```

### GRAFICO

```{r grafico}
grafico_ggplot2 <-
  cantones %>%
  st_drop_geometry() %>%
  slice_max(area, n = 5) %>%
  ggplot(aes(x = reorder(canton, -area), y = area)) +
  geom_bar(stat = "identity")

ggplotly(grafico_ggplot2)

```

